<a href="https://colab.research.google.com/github/UmitOzteker/TensorFlow-Projects/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
#tf.constant() ile tensorlar oluşturma
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

#Tf.constant Tensör benzeri bir nesneden sabit bir tensör oluşturur.

In [5]:
# Bir Tensorun Boyut sayısını kontrol etme
scalar.ndim # ndim= number of dimensions

0

In [6]:
# Vector oluşturma
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Vectorün boyutunu ölçme
vector.ndim

1

In [8]:
# Matrix Oluşturma
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Başka matrix oluşturma
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9,]],dtype =tf.float16) # dtype parametresi değiştirme default = int32
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Tensor oluşturma
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

### tf.Variable ile Tensorler oluşturma
TensorFlow değişkeni, programınızın yönettiği paylaşılan, kalıcı durumu temsil etmenin önerilen yoludur.

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Tensorun elementini değiştirme
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
#Constant eleman değiştireilemez
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random Tensorler Oluşturma

Rastgele tensörler, rastgele sayılar içeren bazı ikili büyüklükteki tensörlerdir.

Bu, sinir ağlarının verilerde öğrenmeye çalıştıkları ağırlıkları (örüntüleri) başlatmak için kullandıkları şeydir.

Örneğin, bir sinir ağı öğrenme süreci genellikle rastgele n boyutlu bir sayı dizisini almayı ve bunları bir tür modeli temsil edene kadar (orijinal verileri temsil etmenin sıkıştırılmış bir yolu) hassaslaştırmayı içerir.



In [ ]:
random_1 = tf.random.Generator.from_seed(42) # tekrarlanabilirlik için tohumu ayarlama
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
#Eşitlik Ölçümü
random_1, random_2 , random_1==random_2

#Shape:
Oluşturulacak tensörün şeklini belirten bir dizi veya tuple. Örneğin, (3, 4) şeklinde bir tensör, 3 satır ve 4 sütun içeren bir matris oluşturur.

#Tensorflow rastgele tohum nedir?
Rastgele bir tohuma dayanan operasyonlar aslında onu iki tohumdan türetir: küresel ve operasyon düzeyindeki tohumlar. Bu küresel tohumu belirler. Operasyon seviyesindeki tohumlarla etkileşimleri şu şekildedir: Ne global tohum ne de operasyon tohumu ayarlanmamışsa: Bu işlem için rastgele seçilmiş bir tohum kullanılır.

#Rastgele normal başlatıcı nedir?
random_normal_initializer, tf'yi çağıran bir Başlatıcı örneğidir.

# Bir tensörün sırasını karıştırma
Diyelim ki 15.000 kedi ve köpek resmiyle çalışıyorsunuz ve ilk 10.000 resim kediye, sonraki 5.000 resim ise köpeğe ait. Bu sıra, sinir ağının öğrenme şeklini etkileyebilir (verilerin sırasını öğrenerek aşırı uyum sağlayabilir), bunun yerine verilerinizi taşımak iyi bir fikir olabilir.


In [17]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.shuffle(not_shuffled,seed =42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Neden Rakamlar Aynı Çıkmadı?
Bunun nedeni tf.random.set_seed() belgelerinin 4 numaralı kuralıdır.

"4. Hem global hem de operasyon tohumu ayarlanmışsa: Her iki tohum da rastgele sırayı belirlemek için birlikte kullanılır."

tf.random.set_seed(42) global çekirdeği ayarlar ve tf.random.shuffle(seed=42) içindeki tohum parametresi işlem tohumunu ayarlar.

Çünkü, "Rastgele bir tohuma dayanan operasyonlar aslında onu iki tohumdan türetir: Küresel ve operasyon düzeyindeki tohumlardan. Bu, küresel tohumu belirler."

# Tensor oluşturmanın başka yolları

In [19]:
# Tüm tensorler 1
tf.ones([8,88])

<tf.Tensor: shape=(8, 88), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
     

In [20]:
# Tüm tensorler sıfır
tf.zeros(shape = (3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Tensörler ile NumPy dizileri arasındaki temel fark, tensörlerin GPU'larda çalıştırılabilmesidir.

In [21]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #1 ila 25 arası dizi oluşturur
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Tensorlerden Bilgi Alma
* Şekil: Bir tensörün her boyutunun uzunluğu (eleman sayısı).
* Sıra: Tensör boyutlarının sayısı. Bir skaler rütbe 0'a, bir vektör derece 1'e, bir matris derece 2'ye, bir tensör derece n'ye sahiptir.
* Eksen veya Boyut: Bir tensörün belirli bir boyutu.
* Boyut: Tensördeki toplam öğe sayısı.





In [23]:
# 4. derece tensör oluşturma (4 boyut)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
# Tensörün çeşitli özelliklerini alın
print("Her öğenin veri türü", rank_4_tensor.dtype)
print("Boyut sayısı (sıralama):",rank_4_tensor.ndim)
print("Tensörün şekli:",rank_4_tensor.shape)
print("Tensörün 0 ekseni boyunca elemanları:",rank_4_tensor.shape[0])
print("Tensörün son ekseni boyunca elemanlar:",rank_4_tensor.shape[-1])
print("Toplam öğe sayısı (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() NumPy dizisine dönüştürür

Her öğenin veri türü <dtype: 'float32'>
Boyut sayısı (sıralama): 4
Tensörün şekli: (2, 3, 4, 5)
Tensörün 0 ekseni boyunca elemanları: 2
Tensörün son ekseni boyunca elemanlar: 5
Toplam öğe sayısı (2*3*4*5): 120


#Tensörleri de Python listeleri gibi indeksleyebilme

In [27]:
# Her boyutun ilk 2 öğesini alın
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# Sonuncusu hariç her dizinden boyutu alma
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# 2. derece tensör oluşturun (2 boyut)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
# Her satırın son öğesini alın
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

Ayrıca tf.newaxis'i kullanarak aynı bilgiyi mevcut tutarken tensörünüze boyutlar da ekleyebilirsiniz.


In [30]:
# Ekstra bir boyut ekleyin
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Python'da "..." "önceki tüm boyutlar" anlamına gelir
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [31]:
# tf.newaxis alternatifi
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Tensorleri Manipüle Etmek
Tensörlerdeki kalıpları bulmak (verilerin sayısal gösterimi), bunların manipüle edilmesini gerektirir.

Yine TensorFlow'da modeller oluştururken bu model keşfinin büyük bir kısmı sizin için yapılır.

#Basic operations
+, -, * gibi Python operatörlerini kullanarak temel matematik işlemlerinin çoğunu doğrudan tensörler üzerinde gerçekleştirebilirsiniz.

In [32]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10
# Tensor Değişmiyor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [35]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix Çarpımı
İç boyutlar eşleşmelidir:

(3, 5) @ (3, 5) Çalışmaz

(5, 3) @ (3, 5) Çalışır

(3, 5) @ (5, 3) Çalışır

Ortaya çıkan matris dış boyutların şekline sahip olmalı:

(5, 3) @ (3, 5) -> (5, 5)

(3, 5) @ (5, 3) -> (3, 3)

In [36]:
#Matrix Multiplication
print(tensor)
tf.matmul(tensor,tensor) #a matrisini b matrisiyle çarparak a * b sonucunu verir.

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
# "@" operatörü ile Matrix çarpımı
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [38]:
# (3, 2) Tensor oluşturma
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Başka (3, 2) Tensor Oluşturma

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [39]:
# Aynı shape sahip matrixleri çarpmayı deneme
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [50]:
# Y'nin şeklini değiştirme
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [51]:
# X ile Değiştirilmiş Y'nin çarpımı
X @ tf.reshape(Y, shape= (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [40]:
tf.matmul(X, tf.reshape(Y, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

# Maximum ve Minimum Bulma

*   tf.argmax() - belirli bir tensördeki maksimum elemanın konumunu bulur.
*   tf.argmin() - belirli bir tensördeki minimum elemanın konumunu bulur.



In [42]:
tf.random.set_seed(42)
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.36357525, 0.4908213 , 0.54479334, 0.11691394, 0.93252223,
       0.52167576, 0.07094549, 0.24859407, 0.67002454, 0.23117585,
       0.75114495, 0.25133401, 0.0014821 , 0.36991062, 0.46670424,
       0.51499813, 0.01188781, 0.55061008, 0.52034782, 0.30121189,
       0.01059077, 0.89089439, 0.05648906, 0.28432871, 0.2417539 ,
       0.53219574, 0.72913696, 0.87184387, 0.17143421, 0.88308215,
       0.92246773, 0.78104466, 0.71528891, 0.55163778, 0.79603023,
       0.66293586, 0.41999394, 0.92311352, 0.67376544, 0.3112272 ,
       0.63342495, 0.37408074, 0.34855574, 0.75404209, 0.3871619 ,
       0.16014628, 0.90720317, 0.29768599, 0.4331269 , 0.72233218])>

In [44]:
# Pozisyonal Maximumu bulma
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [46]:
np.argmax(F)

4

In [47]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9325222275222672>

In [48]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9325222275222672>

In [49]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [52]:
# Minimum Bulma
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [53]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.0014821001927022293>

### Tensoru Sıkıştırmak (Tüm tek boyutları silme)

Bir tensörden tek boyutları kaldırmanız gerekiyorsa (boyut 1 olan boyutlar), tf.squeeze() öğesini kullanabilirsiniz.

Tensorler, veri işleme ve model eğitimi gibi birçok alanda kullanılan çok boyutlu dizilerdir. Tensorlerin sıkıştırılması bazı durumlarda önemlidir:

* **Veri Boyutunu Azaltmak**: Büyük veri setleri veya yüksek çözünürlüklü görüntüler gibi büyük boyutlu tensorler, bellek ve işlem gücü açısından maliyetli olabilir. Sıkıştırma, bu boyutları azaltarak daha verimli bir işlem yapmayı sağlar.
* **Veri Aktarımı ve Depolama**: Büyük tensorlerin ağ üzerinden iletilmesi veya diskte saklanması zaman alabilir. Sıkıştırma, veri aktarımını hızlandırır ve depolama alanını azaltır.
* **Model Eğitimi ve Enkodlama**: Derin öğrenme modelleri, büyük veri setleri üzerinde eğitildiğinde sıkıştırma önemlidir. Ayrıca, veri enkodlama ve sıkıştırma algoritmaları, veri boyutunu azaltarak daha hızlı ve daha az bellek tüketen modeller oluşturmayı sağlar.
* **Görüntü ve Ses İşleme**: Görüntü ve ses verileri sıkıştırılarak daha hızlı işlenebilir. Örneğin, JPEG ve MP3 gibi sıkıştırma algoritmaları, bu tür verileri daha küçük boyutlarda temsil eder.
* **Veri Gizliliği**: Sıkıştırma, veri gizliliğini artırabilir. Özellikle hassas verilerin paylaşılması veya depolanması gerektiğinde, sıkıştırma algoritmaları kullanılabilir.
Sonuç olarak, tensor sıkıştırma, veri boyutunu azaltmak, işlem hızını artırmak ve veri yönetimini optimize etmek için önemlidir.

*   tf.squeeze() - Tensorun tek boyutlarını siler


In [55]:
G = tf.constant(np.random.random(50), shape =(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float64, numpy=
array([[[[[0.09430778, 0.29811629, 0.59586756, 0.09300062, 0.44719429,
           0.80346472, 0.01306664, 0.89172622, 0.19088346, 0.7154638 ,
           0.80194013, 0.84088121, 0.12152255, 0.00625763, 0.09749072,
           0.60441827, 0.88157061, 0.10783322, 0.0865251 , 0.41808433,
           0.60057856, 0.12715606, 0.64088644, 0.08982456, 0.26155474,
           0.66699836, 0.09372739, 0.07780707, 0.24487213, 0.03770072,
           0.57472665, 0.64896652, 0.97684335, 0.78973437, 0.42835112,
           0.12326014, 0.7129856 , 0.12353382, 0.5103423 , 0.89153854,
           0.99544462, 0.21195714, 0.28326716, 0.13052371, 0.6893866 ,
           0.33770464, 0.76885696, 0.93978177, 0.46496807, 0.5148523 ]]]]])>

In [57]:
G.shape


TensorShape([1, 1, 1, 1, 50])

In [58]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float64, numpy=
 array([0.09430778, 0.29811629, 0.59586756, 0.09300062, 0.44719429,
        0.80346472, 0.01306664, 0.89172622, 0.19088346, 0.7154638 ,
        0.80194013, 0.84088121, 0.12152255, 0.00625763, 0.09749072,
        0.60441827, 0.88157061, 0.10783322, 0.0865251 , 0.41808433,
        0.60057856, 0.12715606, 0.64088644, 0.08982456, 0.26155474,
        0.66699836, 0.09372739, 0.07780707, 0.24487213, 0.03770072,
        0.57472665, 0.64896652, 0.97684335, 0.78973437, 0.42835112,
        0.12326014, 0.7129856 , 0.12353382, 0.5103423 , 0.89153854,
        0.99544462, 0.21195714, 0.28326716, 0.13052371, 0.6893866 ,
        0.33770464, 0.76885696, 0.93978177, 0.46496807, 0.5148523 ])>,
 TensorShape([50]))

# One-Hot Encoding
One Hot Encoding, kategorik verilerin daha etkili ve kolay bir şekilde temsil edilmesini sağlar

Bir indis tensörünüz varsa ve bunu tek seferde kodlamak istiyorsanız tf.one_hot() öğesini kullanabilirsiniz.

Ayrıca derinlik parametresini de (tek seferde kodlamak istediğiniz seviye) belirtmelisiniz.

In [64]:
some_list = [0, 1, 2, 3]

# One-hot encoding işlemi
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [66]:
# One Hot Encoding için Özel Değerler
tf.one_hot(some_list, depth = 4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

# Karekök, Kare Alma ve Log İşlemleri

In [70]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [71]:
# Karesini Alma
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

Karekök ve logaritma İşlemi için tensor İnteger olmamalıdır.

In [75]:
# Karekök Alma
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [78]:
# Log Bulma
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>