<a href="https://colab.research.google.com/github/UmitOzteker/TensorFlow-Projects/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [67]:
#tf.constant() ile tensorlar oluşturma
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

#Tf.constant Tensör benzeri bir nesneden sabit bir tensör oluşturur.

In [68]:
# Bir Tensorun Boyut sayısını kontrol etme
scalar.ndim # ndim= number of dimensions

0

In [69]:
# Vector oluşturma
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [70]:
# Vectorün boyutunu ölçme
vector.ndim

1

In [71]:
# Matrix Oluşturma
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [72]:
matrix.ndim

2

In [73]:
# Başka matrix oluşturma
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9,]],dtype =tf.float16) # dtype parametresi değiştirme default = int32
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [74]:
another_matrix.ndim

2

In [75]:
# Tensor oluşturma
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [76]:
tensor.ndim

3

### tf.Variable ile Tensorler oluşturma
TensorFlow değişkeni, programınızın yönettiği paylaşılan, kalıcı durumu temsil etmenin önerilen yoludur.

In [77]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [78]:
# Tensorun elementini değiştirme
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [79]:
#Constant eleman değiştireilemez
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random Tensorler Oluşturma

Rastgele tensörler, rastgele sayılar içeren bazı ikili büyüklükteki tensörlerdir.

Bu, sinir ağlarının verilerde öğrenmeye çalıştıkları ağırlıkları (örüntüleri) başlatmak için kullandıkları şeydir.

Örneğin, bir sinir ağı öğrenme süreci genellikle rastgele n boyutlu bir sayı dizisini almayı ve bunları bir tür modeli temsil edene kadar (orijinal verileri temsil etmenin sıkıştırılmış bir yolu) hassaslaştırmayı içerir.



In [80]:
random_1 = tf.random.Generator.from_seed(42) # tekrarlanabilirlik için tohumu ayarlama
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
#Eşitlik Ölçümü
random_1, random_2 , random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#Shape:
Oluşturulacak tensörün şeklini belirten bir dizi veya tuple. Örneğin, (3, 4) şeklinde bir tensör, 3 satır ve 4 sütun içeren bir matris oluşturur.

#Tensorflow rastgele tohum nedir?
Rastgele bir tohuma dayanan operasyonlar aslında onu iki tohumdan türetir: küresel ve operasyon düzeyindeki tohumlar. Bu küresel tohumu belirler. Operasyon seviyesindeki tohumlarla etkileşimleri şu şekildedir: Ne global tohum ne de operasyon tohumu ayarlanmamışsa: Bu işlem için rastgele seçilmiş bir tohum kullanılır.

#Rastgele normal başlatıcı nedir?
random_normal_initializer, tf'yi çağıran bir Başlatıcı örneğidir.

# Bir tensörün sırasını karıştırma
Diyelim ki 15.000 kedi ve köpek resmiyle çalışıyorsunuz ve ilk 10.000 resim kediye, sonraki 5.000 resim ise köpeğe ait. Bu sıra, sinir ağının öğrenme şeklini etkileyebilir (verilerin sırasını öğrenerek aşırı uyum sağlayabilir), bunun yerine verilerinizi taşımak iyi bir fikir olabilir.


In [81]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.shuffle(not_shuffled,seed =42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [82]:
# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Neden Rakamlar Aynı Çıkmadı?
Bunun nedeni tf.random.set_seed() belgelerinin 4 numaralı kuralıdır.

"4. Hem global hem de operasyon tohumu ayarlanmışsa: Her iki tohum da rastgele sırayı belirlemek için birlikte kullanılır."

tf.random.set_seed(42) global çekirdeği ayarlar ve tf.random.shuffle(seed=42) içindeki tohum parametresi işlem tohumunu ayarlar.

Çünkü, "Rastgele bir tohuma dayanan operasyonlar aslında onu iki tohumdan türetir: Küresel ve operasyon düzeyindeki tohumlardan. Bu, küresel tohumu belirler."

# Tensor oluşturmanın başka yolları

In [ ]:
# Tüm tensorler 1
tf.ones([8,88])

In [85]:
# Tüm tensorler sıfır
tf.zeros(shape = (3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Tensörler ile NumPy dizileri arasındaki temel fark, tensörlerin GPU'larda çalıştırılabilmesidir.

In [86]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #1 ila 25 arası dizi oluşturur
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [87]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Tensorlerden Bilgi Alma
* Şekil: Bir tensörün her boyutunun uzunluğu (eleman sayısı).
* Sıra: Tensör boyutlarının sayısı. Bir skaler rütbe 0'a, bir vektör derece 1'e, bir matris derece 2'ye, bir tensör derece n'ye sahiptir.
* Eksen veya Boyut: Bir tensörün belirli bir boyutu.
* Boyut: Tensördeki toplam öğe sayısı.





In [88]:
# 4. derece tensör oluşturma (4 boyut)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [89]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [90]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [91]:
# Tensörün çeşitli özelliklerini alın
print("Her öğenin veri türü", rank_4_tensor.dtype)
print("Boyut sayısı (sıralama):",rank_4_tensor.ndim)
print("Tensörün şekli:",rank_4_tensor.shape)
print("Tensörün 0 ekseni boyunca elemanları:",rank_4_tensor.shape[0])
print("Tensörün son ekseni boyunca elemanlar:",rank_4_tensor.shape[-1])
print("Toplam öğe sayısı (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() NumPy dizisine dönüştürür

Her öğenin veri türü <dtype: 'float32'>
Boyut sayısı (sıralama): 4
Tensörün şekli: (2, 3, 4, 5)
Tensörün 0 ekseni boyunca elemanları: 2
Tensörün son ekseni boyunca elemanlar: 5
Toplam öğe sayısı (2*3*4*5): 120


#Tensörleri de Python listeleri gibi indeksleyebilme

In [92]:
# Her boyutun ilk 2 öğesini alın
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [93]:
# Sonuncusu hariç her dizinden boyutu alma
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [94]:
# 2. derece tensör oluşturun (2 boyut)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
# Her satırın son öğesini alın
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

Ayrıca tf.newaxis'i kullanarak aynı bilgiyi mevcut tutarken tensörünüze boyutlar da ekleyebilirsiniz.


In [95]:
# Ekstra bir boyut ekleyin
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Python'da "..." "önceki tüm boyutlar" anlamına gelir
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [96]:
# tf.newaxis alternatifi
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Tensorleri Manipüle Etmek
Tensörlerdeki kalıpları bulmak (verilerin sayısal gösterimi), bunların manipüle edilmesini gerektirir.

Yine TensorFlow'da modeller oluştururken bu model keşfinin büyük bir kısmı sizin için yapılır.

#Basic operations
+, -, * gibi Python operatörlerini kullanarak temel matematik işlemlerinin çoğunu doğrudan tensörler üzerinde gerçekleştirebilirsiniz.

In [97]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10
# Tensor Değişmiyor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [98]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [99]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [100]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix Çarpımı
İç boyutlar eşleşmelidir:

(3, 5) @ (3, 5) Çalışmaz

(5, 3) @ (3, 5) Çalışır

(3, 5) @ (5, 3) Çalışır

Ortaya çıkan matris dış boyutların şekline sahip olmalı:

(5, 3) @ (3, 5) -> (5, 5)

(3, 5) @ (5, 3) -> (3, 3)

In [101]:
#Matrix Multiplication
print(tensor)
tf.matmul(tensor,tensor) #a matrisini b matrisiyle çarparak a * b sonucunu verir.

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [102]:
# "@" operatörü ile Matrix çarpımı
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [103]:
# (3, 2) Tensor oluşturma
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Başka (3, 2) Tensor Oluşturma

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [104]:
# Aynı shape sahip matrixleri çarpmayı deneme
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Y'nin şeklini değiştirme
tf.reshape(Y, shape=(2,3))

In [ ]:
# X ile Değiştirilmiş Y'nin çarpımı
X @ tf.reshape(Y, shape= (2,3))

In [105]:
tf.matmul(X, tf.reshape(Y, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [106]:
# Transpose ile reshape yapımı
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

# Transpose:
Transpose kolon ve sütunun yerlerini değiştirir

In [107]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# Dot Product
Değer olarak iki vektör alan ve sonuç olarak skaler bir değer döndüren işleme denir.

Matrix çarpımı *tf.matmul* ve *tf.tensordot* kullanılarak yapılabilir

# Tensordot:

Tensordot (tensör daralması olarak da bilinir), eksenlerle belirtilen indeksler üzerinden a ve b'deki elemanların çarpımını toplar.

Bu işlem numpy.tensordot(a, b, axes) işlemine karşılık gelir.

Örnek 1: a ve b matrisler olduğunda (2. dereceden), eksen=1 durumu matris çarpımına eşdeğerdir.

Örnek 2: a ve b matrisler olduğunda (2. sıra), eksenler = [[1], [0]] durumu matris çarpımına eşdeğerdir.

Örnek 3: a ve b matrisler olduğunda (2. dereceden), eksenler=0 durumu 4. dereceden bir tensör olan dış çarpımı verir.


In [108]:
# X ve Y için dot product kullanımı (X veya Y'nin transpose edilmesi gerekmektedir.)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [109]:
# Tranpose kullanarak X ve Y matrixinin çarpılması
tf.matmul(X , tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [110]:
# Reshape kullanarak X ve Y Matrixlerinin çarpılması
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [111]:
# Y, reshape edilmiş Y ve Transpose edilmiş Y'nin kontrol edilmesi
print("Normal Y:")
print(Y, "\n")

print("(2,3)'e reshape edilmiş Y:")
print(tf.reshape(Y, shape=(2,3)),"\n")

print("Transposed edilmiş Y:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

(2,3)'e reshape edilmiş Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed edilmiş Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Tensorün Data tipini değiştirme

In [112]:
# default datatip (float32) ile yeni bir tensor oluşturma
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [113]:
C = tf.constant([7,10])
C.dtype

tf.int32

# Mixed Precision
Karma hassasiyet, bir modelin daha hızlı çalışmasını ve daha az bellek kullanmasını sağlamak için eğitim sırasında bir modelde hem 16 bit hem de 32 bit kayan nokta türlerinin kullanılmasıdır. Sayısal kararlılık için modelin belirli kısımları 32 bitlik tiplerde tutularak, model daha düşük adım süresine sahip olacak ve doğruluk gibi değerlendirme ölçütleri açısından da eşit olarak eğitilecektir. Bu kılavuz, modellerinizi hızlandırmak için Keras karma hassas API'sinin nasıl kullanılacağını açıklar. Bu API'yi kullanmak, performansı modern GPU'larda 3 kattan ve TPU'larda %60'tan fazla artırabilir.

In [114]:
# float32'yi float16'ya dönüştürme (reduced precision
D = tf.cast(B, dtype=tf.float16)
D


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [115]:
# int32'yi float32'ye dönüştürme
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# Tensorleri Toplama

Tüm öğelerin minimum değeri, maksimum değeri, ortalaması ve toplamı gibi şeyleri bulmak için tensörleri hızla toplayabilirsiniz (tüm tensör üzerinde hesaplama yapabilirsiniz).

Bunu yapmak için toplama yöntemleri genellikle aşağıdaki gibi reduce()_[action] sözdizimine sahiptir:

tf.reduce_min() - tensördeki minimum değeri bulun.

tf.reduce_max() - tensördeki maksimum değeri bulun (en yüksek tahmin olasılığını bulmak istediğinizde faydalıdır).

tf.reduce_mean() - bir tensördeki tüm öğelerin ortalamasını bulun.

tf.reduce_sum() - bir tensördeki tüm elemanların toplamını bulun.

Not: Tipik olarak bunların her biri matematik modülünün altındadır, ör. tf.math.reduce_min() ancak tf.reduce_min() takma adını kullanabilirsiniz.


In [116]:
# Kesin değeri bulma
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [117]:
# Kesin değeri bulma
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [119]:
# Random tensor oluşturma 50 haneli 0 ile
E = tf.constant(np.random.randint(0, 100, size = 50)) #Rastgele tamsayıları düşükten (dahil) yükseğe (hariç) döndürür
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 69, 92, 67, 12, 87, 67, 96, 91, 65, 37, 93, 96, 20, 65, 93, 87,
       29, 16, 79, 95, 44, 42, 52, 14, 22,  9, 76, 18, 90,  1, 31, 90, 89,
       74, 52, 75, 87,  0, 27, 74,  3, 30, 87, 96, 73, 21, 49, 43,  6])>

In [120]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [121]:
#Minimum Bulma
tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [124]:
# Maximum Bulma
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [125]:
# Ortalama Bulma
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [126]:
# Toplam Bulma
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2827>

In [133]:
# Tensor Varyansı Bulma
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1022>

In [134]:
# Standart deviationu bulma
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.978874>